version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8005
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    expose:
      - 8005
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: