# Generated by Django 2.1.15 on 2021-04-08 23:17

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleURLLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slicename', models.CharField(max_length=150)),
                ('TargetSNR', models.FloatField(default=0.0)),
                ('numberofUsers', models.IntegerField(default=1)),
                ('numerologyID', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('sharedBandwidth', models.FloatField(default=0.0)),
                ('reservedBandwidth', models.FloatField(default=0.0)),
                ('channelGainShadowParam1', models.FloatField(blank=True, null=True)),
                ('channelGainFadeParam1', models.FloatField(blank=True, null=True)),
                ('channelGainFadeParam2', models.FloatField(blank=True, null=True)),
                ('power', models.FloatField(default=0.0)),
                ('trafficDist', models.CharField(max_length=150)),
                ('trafficParam1', models.FloatField(blank=True, null=True)),
                ('trafficParam2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='site',
            name='sensors',
        ),
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
