# Generated by Django 2.1.15 on 2021-04-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210408_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='observerInSitesIds',
        ),
        migrations.RemoveField(
            model_name='user',
            name='operatorInSitesIds',
        ),
    ]
